name: DataSketches-Java Auto JDK Matrix Test & Install

on:
    pull_request:
    push:
        branches: [ master ]
    workflow_dispatch:

env:
    MAVEN_OPTS: -Xmx4g -Xms1g #for JVM

jobs:
    build:
        name: Build, Test, Install
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
              jdk: [ 8,11 ]
        env:
          JDK_VERSION: ${{ matrix.jdk }}

        steps:
        - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
          uses: actions/checkout@v3
          with:
              persist-credentials: false

        - name: Cache local Maven repository
          uses: actions/cache@v3
          with:
              path: ~/.m2/repository
              key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: build-${{ runner.os }}-maven-

        - name: Install Matrix JDK
          uses: actions/setup-java@v3
          with:
              java-version: ${{ matrix.jdk }}
              distribution: 'temurin'
              java-package: jdk
              architecture: x64 #options: x86, x64, armv7, aarch64, ppc64le
              #cache #option

        - name: Echo Java Version
          run: >
              java -version

        - name: Test
          run: >
              mvn clean test
              -Dmaven.javadoc.skip=true
              -Dgpg.skip=true

        - name: Install
          run: >
              mvn clean install -B -q
              -DskipTests=true
              -Dgpg.skip=true

