name: Java CI with Maven, Coveralls

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        env: MAVEN_OPTS="-Xmx4g -Xms1g"
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
              java-version: 1.8  #OR 8.0.212 | 16.0.0-ea.28 (.28 is build #)

        - name: Maven clean test
          run: mvn clean test jacoco:report coveralls:report -q -Dgpg.skip=true -DisDebugEnabled=true --batch-mode

        - name: Coveralls
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.github_token }}