name: Java CI with Maven, Coveralls

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    MAVEN_OPTS: -Xmx4g -Xms1g

jobs:
    build:
        name: Build Job
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
              java-version: 1.8  #OR 8.0.212 | 16.0.0-ea.28 (.28 is build #)

        - name: Maven clean test
          run: mvn clean test jacoco:report -q -Dgpg.skip=true -DisDebugEnabled=true --batch-mode --file=pom.xml

        - name: Coveralls
          if: ${{ success() }}
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.github_token }}