name: Test Java with OS Matrix

on:
    workflow_dispatch:
        
env:
    MAVEN_OPTS: -Xmx4g -Xms1g

jobs:
    build:
        name: Build, Test, Coverage
        runs-on: ${{matrix.os}}
        strategy:
          fail-fast: false
          matrix:
            #jdk: [ 8,11,12,13 ]
            jdk: [ 8 ]
            # OS options: windows-latest, ubuntu-latest, macos-latest
            os: [ windows-latest, ubuntu-latest, macos-latest ]
            include:
              - os: windows-latest
                skip_javadoc: "`-Dmaven`.javadoc`.skip=true"
                skip_gpg: "`-Dgpg`.skip=true"
              - os: ubuntu-latest
                skip_javadoc: -Dmaven.javadoc.skip=true
                skip_gpg: -Dgpg.skip=true
              - os: macos-latest
                skip_javadoc: -Dmaven.javadoc.skip=true
                skip_gpg: -Dgpg.skip=true

        env:
          JDK_VERSION: ${{ matrix.jdk }}

        steps:
        - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
          uses: actions/checkout@v3
          with:
              persist-credentials: false

        - name: Cache local Maven repository
          uses: actions/cache@v3
          with:
              path: ~/.m2/repository
              key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: build-${{ runner.os }}-maven-

        - name: Install Matrix JDK
          uses: AdoptOpenJDK/install-jdk@v1
          with:
              version: ${{ matrix.jdk }}
              architecture: x64
              impl: hotspot
              targets: 'JAVA_HOME'

        - name: Echo Java Version
          run: >
              java -version

        - name: Test
          run: >
              mvn clean test
              ${{matrix.os.skip_javadoc}}
              ${{matrix.os.skip_gpg}}

        - name: Install Dependencies
          run: >
              #-B batch mode, -V show Version without stoppping, -q quiet, only show errors
              mvn clean install -B -V -q
              -D skipTests=true
              ${{matrix.os.skip_gpg}}

        - name: Report
          if: ${{ matrix.jdk == 8 && success() }}
          run: >
              #Lifecycle:validate,compile,test,package,verify,install,deploy
              #test and coverage reports are available after the verify phase
              #Javadocs are available after compile
              mvn verify coveralls:report -B -V -q
              -DrepoToken=${{secrets.coveralls_token}}
              ${{matrix.os.skip_javadoc}}
              ${{matrix.os.skip_gpg}}
